"""empty message

Revision ID: 19eb323d25e5
Revises: b5cb47834837
Create Date: 2017-09-29 01:35:02.542573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19eb323d25e5'
down_revision = 'b5cb47834837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fb_id', sa.BigInteger(), nullable=True))
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'user', ['fb_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'is_deleted')
    op.drop_column('user', 'fb_id')
    # ### end Alembic commands ###
