"""empty message

Revision ID: aed231807c25
Revises: 19eb323d25e5
Create Date: 2017-09-29 01:45:28.217595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed231807c25'
down_revision = '19eb323d25e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fb_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fb_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fb_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fb_user_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='fb_user_pkey'),
    sa.UniqueConstraint('fb_id', name='fb_user_fb_id_key')
    )
    # ### end Alembic commands ###
