"""empty message

Revision ID: b5cb47834837
Revises: 7a65c7f155e7
Create Date: 2017-09-26 00:33:19.718226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5cb47834837'
down_revision = '7a65c7f155e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('verification_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'verification_code')
    # ### end Alembic commands ###
